### ISSUE TITLE
running pygrambank in new repos

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#101]
For the ELAR-Glottobank grants we're getting the grantees to submit their completed glottobank data sheets (numeralbank, lexibank and grambank) in a new repos, over here: https://github.com/glottobank/ELDP-glottobank/wiki/ELAR-archving

I'd like to run pygrambank commands on them before incorproration. Is what I need to do just copy over gb.bib to that repos and the rest of pygrambank commands will work well? and maybe also gb20.txt?

**Comment by xrotwang** [comment]
The repos should look like the one we use for the pygrambank test suite: https://github.com/grambank/pygrambank/tree/master/tests/repos - minus "archived_discussions" and "obsolete_sheets".

**Comment by HedvigS** [comment]
Okay. But things don't need to be in a dir called "original_sheets" right?

Is it okay if I add you to the repos and you can see what it's like?

**Comment by xrotwang** [comment]
Sheets must be in `original_sheets`, see https://github.com/grambank/pygrambank/blob/5da12be65bc80cb5900df630584c195fbfdaaf28/src/pygrambank/api.py#L21-L23

**Comment by xrotwang** [comment]
`pygrambank` also only accepts Grambank sheets, so the lexical data would need to be in a separate directory.

**Comment by HedvigS** [comment]
yes, I placed them in different dirs already

**Comment by HedvigS** [comment]
[Does this look right now?](https://github.com/glottobank/ELDP-glottobank/tree/main/grambank)

**Comment by xrotwang** [comment]
Seems ok:
```shell
$ grambank --repos grambank/ stats
<grambank repository grambank at grambank>

Sheets with BOM:

1 sheets with 245 rows

Most common columns:
Feature_ID 1
Value 1
Source 1
Comment 1
Contributed_Datapoints 1
```

**Comment by HedvigS** [comment]
Cool, nice! So once the grantees send in sheets, we'll put them in that dir and run pygrambank sheets on PRs like we do elsewhere. Sweet!

**Comment by xrotwang** [comment]
ad 2.) Here's what `csvstat` says:
```
14. "Value "

	Type of data:          Number
	Contains null values:  False
	Unique values:         4
	Smallest value:        0,
	Largest value:         3,
	Sum:                   72,
	Mean:                  0,369
	Median:                0,
	StDev:                 0,553
	Most common values:    0, (128x)
	                       1, (64x)
	                       3, (2x)
	                       2, (1x)
```
i.e. the "Value" column is actually called `Value ` - with trailing space.

**Comment by xrotwang** [comment]
ad 3.) The `Contribution` column is currently required, too. Should that be set to a default - say `Coder`?

**Comment by HedvigS** [comment]
> ad 2.) Here's what `csvstat` says:
> 
> ```
> 14. "Value "
> 
> 	Type of data:          Number
> 	Contains null values:  False
> 	Unique values:         4
> 	Smallest value:        0,
> 	Largest value:         3,
> 	Sum:                   72,
> 	Mean:                  0,369
> 	Median:                0,
> 	StDev:                 0,553
> 	Most common values:    0, (128x)
> 	                       1, (64x)
> 	                       3, (2x)
> 	                       2, (1x)
> ```
> 
> i.e. the "Value" column is actually called `Value ` - with trailing space.

Ah, that had passed me by. Updating now.

**Comment by HedvigS** [comment]
> ad 3.) The `Contribution` column is currently required, too. Should that be set to a default - say `Coder`?

You mean `Contributed_Datapoints`? That exists for both sheets in: https://github.com/glottobank/ELDP-glottobank/tree/SGI_submission_yurakare/grambank/original_sheets

**Comment by HedvigS** [comment]
> 3)  i gave pygrambank describe the other sheet which is there and which I know is correct, and then it struggled with the column "round" in the contributors.md. Can it please be told to ignore any columns that aren't what it needs?

This is still a factor. Can pygrambank describe/sheet please ignore all columns in contributors.md that it doesn't need?
```

(Grambank) skirgard@lingd08 ELDP-glottobank % grambank describe grambank/original_sheets/JLA_yura1255.tsv


Path:
grambank/original_sheets/JLA_yura1255.tsv

Check:

Dimensions:
195 rows
17 columns

Values:
0	128
1	 64
3	  2
2	  1
	195

Sources:
Gijn 2006:	196
Gipper (corpus analysis/field notes 2006:	193
Gipper 2011:	  3
Gipper 2017:	  2
Gijn 2004:	  2
Gipper & Yap 2019:	  2
Von Holten 1877:	  2
Gipper 2022:	  1

Coders:
Traceback (most recent call last):
  File "/Users/skirgard/py_venvs/Grambank/bin/grambank", line 11, in <module>
    load_entry_point('pygrambank', 'console_scripts', 'grambank')()
  File "/Users/skirgard/Git/grambank/pygrambank/src/pygrambank/__main__.py", line 36, in main
    return args.main(args) or 0
  File "/Users/skirgard/Git/grambank/pygrambank/src/pygrambank/commands/describe.py", line 45, in run
    describe(args, sheet)
  File "/Users/skirgard/Git/grambank/pygrambank/src/pygrambank/commands/describe.py", line 92, in describe
    coders_by_id = {c.id: c.name for c in args.repos.contributors}
  File "/Users/skirgard/Git/grambank/pygrambank/src/pygrambank/api.py", line 38, in contributors
    return Contributors.from_md(self.repos / 'CONTRIBUTORS.md')
  File "/Users/skirgard/Git/grambank/pygrambank/src/pygrambank/contributors.py", line 67, in from_md
    rows = [Contributor(**dict(zip([norm_header(c) for c in header], row))) for row in rows]
  File "/Users/skirgard/Git/grambank/pygrambank/src/pygrambank/contributors.py", line 67, in <listcomp>
    rows = [Contributor(**dict(zip([norm_header(c) for c in header], row))) for row in rows]
TypeError: __init__() got an unexpected keyword argument 'round'
```

**Comment by HedvigS** [comment]
I thought that the only thing pygrambank would want with contributors.md is that the coder abbreviation in the filename or in the column "Contributed_Datapoint"-column exists. I don't think any of the functions need to check anything beyond that?

**Comment by xrotwang** [comment]
I closed, because I implemented a fix, here https://github.com/grambank/pygrambank/commit/e40d073ebbc91cab08a373b11ace951bea59d719
Do you need a proper release of pygrambank or can you update your clone of pygrambank?

**Comment by xrotwang** [comment]
> I thought that the only thing pygrambank would want with contributors.md is that the coder abbreviation in the filename or in the column "Contributed_Datapoint"-column exists. I don't think any of the functions need to check anything beyond that?

pygrambank validates the content in CONTRIBUTORS.md. The way this is done distinguishes between required and optional columns. So far, `Contribution` was among the required columns - simply because it's there in glottobank/Grambank and always filled in. My question was whether we should assume a default `Contribution` role of `Coder` for `CONTRIBUTORS.md` in the ELDP repos.

**Comment by HedvigS** [comment]
> > I thought that the only thing pygrambank would want with contributors.md is that the coder abbreviation in the filename or in the column "Contributed_Datapoint"-column exists. I don't think any of the functions need to check anything beyond that?
> 
> pygrambank validates the content in CONTRIBUTORS.md. The way this is done distinguishes between required and optional columns. So far, `Contribution` was among the required columns - simply because it's there in glottobank/Grambank and always filled in. My question was whether we should assume a default `Contribution` role of `Coder` for `CONTRIBUTORS.md` in the ELDP repos.

Okay, thank you I understand better now.

I don't think that `Contribution `should be required for either the grambank repos or the ELDP-glottobank repos for pygrambank. I think that the only required column should be `id`.

**Comment by xrotwang** [comment]
> I don't think that `Contribution `should be required for either the grambank repos or the ELDP-glottobank repos for pygrambank. I think that the only required column should be `id`.

I'd say a contributor without a name is a bit weird. Also, the other columns **are** there in both cases. So unless we'd want `pygrambank` to become a generic dataset curation tool, I don't see the point in relaxing the requirements further.

**Comment by HedvigS** [comment]
> > I don't think that `Contribution `should be required for either the grambank repos or the ELDP-glottobank repos for pygrambank. I think that the only required column should be `id`.
> 
> I'd say a contributor without a name is a bit weird. 

That seems like a check of contributors.md and not a check of the validity of the sheet, but okay. Make `Last name `and `First name` required then.

> Also, the other columns **are** there in both cases. So unless we'd want `pygrambank` to become a generic dataset curation tool, I don't see the point in relaxing the requirements further.

`Contribution` is not there for the ELDP-Glottobank contributors.md and I'm not sure I'd want to add things needlessly.
I want pygrambank to be a tool that checks the validity of grambank coding sheets. I don't understand what you're after.

**Comment by HedvigS** [comment]
Okay, thanks.

**Comment by HedvigS** [comment]
All good, works well now. Thanks.
