### ISSUE TITLE
command to generate list of unresolved glottolog lookups

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#22]
As I'm going through and sorting out glottolog lookup fails, it would be great to be able to generate the list @xrotwang made [here](https://github.com/glottobank/Grambank/issues/618#issuecomment-662405882) again myself.

**Comment by xrotwang** [comment]
This list is spit out by the `grambank cldf` command - which you should be able to run now. Syntax is https://github.com/glottobank/grambank-cldf/blob/master/RELEASING.md#releasing-the-grambank-data-as-cldf-datset

**Comment by HedvigS** [comment]
I can't seem to run `grambank cldf` fully, trying to problem solve right now. Stuck at the stage right after langs to refs mapping. I think it may have something to do with the glottolog repos. I've got an updated clone of all the relevant reposes listed, but it seems the glottolog repos should contain a glottolog folder(?). I'm not really sure what's going on, I'll try a couple of ideas myself but if there is something that jumps at you Robert please let me know. I'm guessing it's to do with running some part of pyglottolog.

I'm running the following within a virtual python environment where pygrambank is installed:

`grambank --repos /Users/skirgard/Dropbox/Git/Grambank cldf --wiki_repos /Users/skirgard/Dropbox/Git/grambank_grambank/Grambank.wiki/ --glottolog-version v4.1 --cldf_repos /Users/skirgard/Dropbox/Git/grambank-cldf/  /Users/skirgard/Dropbox/Git/glottolog`

tail end of terminal output:
```

Selecting best sheet for zaye1235
195 dps: choosing sheet BHR_zaye1235
195 dps: skipping sheet SR_zaye1235
loading bibs
computing lang-to-refs mapping ...
... done
Traceback (most recent call last):
  File "/Users/skirgard/py_venvs/grambank/bin/grambank", line 8, in <module>
    sys.exit(main())
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/pygrambank/__main__.py", line 150, in main
    return args.main(args) or 0
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/pygrambank/commands/cldf.py", line 34, in run
    create(args.repos, glottolog.dir, args.wiki_repos, args.cldf_repos)
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/pygrambank/cldf.py", line 96, in create
    'https://github.com/glottobank/pygrambank', clone=Path(__file__).parent.parent.parent),
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/pycldf/dataset.py", line 180, in add_provenance
    v = [to_json(vv) for vv in v]
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/pycldf/dataset.py", line 180, in <listcomp>
    v = [to_json(vv) for vv in v]
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/pycldf/dataset.py", line 173, in to_json
    return obj.json_ld()
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/pycldf/dataset.py", line 120, in json_ld
    res['dc:created'] = git_describe(self.clone)
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/clldutils/path.py", line 192, in git_describe
    raise ValueError('cannot describe non-existent directory')
ValueError: cannot describe non-existent directory
```

**Comment by HedvigS** [comment]
Or wait, installing pyclf of course. Hold on

**Comment by HedvigS** [comment]
No.. that's not it. God, I bet it's super obvious and I'm super stupid. Will stare at it for a while longer.

**Comment by xrotwang** [comment]
And all the paths you are passing in do exist?

**Comment by xrotwang** [comment]
Including `/Users/skirgard/Dropbox/Git/grambank_grambank/Grambank.wiki/`?

**Comment by HedvigS** [comment]
I had moved it because of something else, just noticed. Moved it back. Now:

```
loading bibs
computing lang-to-refs mapping ...
... done
Traceback (most recent call last):
  File "/Users/skirgard/py_venvs/grambank/bin/grambank", line 8, in <module>
    sys.exit(main())
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/pygrambank/__main__.py", line 150, in main
    return args.main(args) or 0
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/pygrambank/commands/cldf.py", line 34, in run
    create(args.repos, glottolog.dir, args.wiki_repos, args.cldf_repos)
  File "/Users/skirgard/py_venvs/grambank/lib/python3.7/site-packages/pygrambank/cldf.py", line 166, in create
    lang = glottolog.languoids_by_glottocode[sheet.glottocode]
KeyError: 'east2851'
```

**Comment by xrotwang** [comment]
That's a new glottocode, you'll have to run with `--glottolog-version v4.2.1`.

**Comment by HedvigS** [comment]
Aha okay.

**Comment by HedvigS** [comment]
Uh it looks like it worked! Hurray! Let me inspect these failed glottolog lookups just to see that things make sense :)

**Comment by HedvigS** [comment]
The output or warnings is divided into two parts, the first with the syntax of
`('Maurer', '1968', 'tang1348') 1 `and the second with the syntax of`tang1348 [('Maurer', '1968'), ('Maurer', '1967')]`. Earlier I got only the first part, but the second is actually more helpful. I take it no-one else is really going to run this command so it matters relatively little, but I was a bit surprised to get this output.
